### ISSUE TITLE
Clicking the date picker for a step due date opens all step due date datepickers

### ISSUE THREAD

**Issue by courtneyportnoy** [cmcrew/bloc-goals#2]
Something isn't right with my logic for keeping track of individual date pickers within the ng-repeat of steps. The goal date picker works as expected, but for the steps if you have more than 1 step, all the step due date datepickers are connected and open/close/select a date as if they are 1 datepicker.

**Comment by matstc** [comment]
You had the right idea Courtney! I fixed it so it would close each date picker before opening the new one.

One thing: you can't use objects as keys in a hash. They will all hash to `[object Object]` no matter what their properties are. So you'll need to convert their properties to a unique hash (`$$hashKey` in this case). You can read [more in this SO answer](https://stackoverflow.com/questions/17253765/how-to-load-hash-in-a-loop-using-objects-as-keys-in-javascript#17253776).

Fixed in [this commit](https://github.com/cmcrew/bloc-goals/commit/a5e92f0a542245a1b8abef4db8dd742efd6345a0).
